### ISSUE TITLE
{'trace_0': []} in pickle files

### ISSUE THREAD

**Issue by Werverton** [yzygitzh/Humanoid#10]
Hi, I'm trying to prepare the data like in scripts within "rico" folder, I could run the code, but the pickle files show just an empty dictionary {'trace_0': []}. Do you have a solution? I run the code with python 2.7.18

**Comment by Werverton** [comment]
{'trace_0': [['/home/werverton/DATA/traces/filtered_traces/jp.naver.linecard.android/trace_0/view_hierarchies/5.json', {'interact_type': 0}, (165, 102)], ['/home/werverton/DATA/traces/filtered_traces/jp.naver.linecard.android/trace_0/view_hierarchies/13.json', {'interact_type': 0}, (168, 19)]]}

The data within pickle files must be like this? Is it correct?

**Comment by yzygitzh** [comment]
Hi,

The pickle file is generated from raw traces for model training purpose. As a result, as long as you can feed it into the model, it should be ok.

**Comment by Werverton** [comment]
Hi, thanks for your answer. So after running the prepare_data_humanoid.py the format mentioned above is the expected pickle? 
A dictionary with lists?

like this one: {'trace_0': [['/home/werverton/DATA/traces/filtered_traces/jp.naver.linecard.android/trace_0/view_hierarchies/5.json', {'interact_type': 0}, (165, 102)], ['/home/werverton/DATA/traces/filtered_traces/jp.naver.linecard.android/trace_0/view_hierarchies/13.json', {'interact_type': 0}, (168, 19)]]}?

**Comment by yzygitzh** [comment]
Yes, it should be a list of <screen, action> mapping.

**Comment by Werverton** [comment]
I would like to use the same data to reproduce your model and after that, I want to train other models using different architectures of lstm to a research. And benchmarking them.
