### ISSUE TITLE
Can't pass input based activities

### ISSUE THREAD

**Issue by ItamarM** [yzygitzh/Humanoid#2]
Tested the model on couple applications[1], but I could not pass any input-based activities such as sign up/ log-in and such.

Maybe you should apply some sort of a classifier to identify those classes and act differently.  

[1] https://play.google.com/store/apps/details?id=com.anydo

**Comment by yzygitzh** [comment]
Hi,
Currently Humanoid is not able to automatically pass general signup and log-in activities, because we don't have such training data. You can use DroidBot's [script](https://github.com/honeynet/droidbot/tree/master/script_samples) to pass such activities, if you want.

**Comment by ItamarM** [comment]
Thanks. 
Good job!
