### ISSUE TITLE
assert error

### ISSUE THREAD

**Issue by hxtkyne** [yzygitzh/Humanoid#3]
我发现一个错误，和数据集相关的：
assert(len(gestures) == len(view_tree_tags))  # 操作数目=页面层次结构数目 
请问一下，我下载的数据集中view_tree_tags会缺失，即gesture有的ui，在view_tree_tags里面没有，这个怎么解决啊？你下载的链接是这个吗：http://interactionmining.org/
感激不尽！

**Comment by yzygitzh** [comment]
Hi,
Yes, I downloaded the dataset from that link. Maybe they've updated their data. I think you can just skip assert fail cases if there aren't too many of them.

**Comment by hxtkyne** [comment]
Thank you ！
