### ISSUE TITLE
Tensorflow errors

### ISSUE THREAD

**Issue by Werverton** [yzygitzh/Humanoid#7]
I'm trying to test humanoid, but I'm getting this error.
my env is: 
debian 10
tensorflow 1.15 no gpu support

file "agent.py", line 16, in <module>
    tf_config.gpu_options.allow_growth = True
AttributeError: 'google.protobuf.pyext._message.FieldProperty' object has no attribute 'allow_growth'

Do anyone know any solution?

**Comment by yzygitzh** [comment]
Please try tensorflow of earlier version, say between 1.8 and 1.12.

**Comment by Werverton** [comment]
Do you have a docker image of humanoid? I'm trying to reproduce it, but I'm had a lot of problems with the environment. Mainly with older versions of tensorflow , I tried compile from source the older version, but I'm not successfully.
