### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by licollins** [yzygitzh/Humanoid#9]
Hello,

I am using Python 3.8.5, tensorflow 2.7.0. I followed all installation steps and when trying to run I get this error:

"ModuleNotFoundError: No module named 'tensorflow.contrib'"

How to solve this problem?

**Comment by Werverton** [comment]
Hello, I'm not the author's project, but I runned the code.
about python version you have to use the version 3.5 or 3.6 and install the version 1.12 of tensorflow.

**Comment by licollins** [comment]
Thanks, I created a new environment with python 3.6 and TensorFlow 1,12 on anaconda and it worked.
